import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/MuiNextLink';
import { Stack } from '@mui/material';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>web3-react with nft merkle tree minting scaffold</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          NFT Lazy Minting with Merkle Whitelist
        </h1>

        <p className={styles.description}>
          <Stack spacing={1}>
            <p>
              Bootstrap an NFT minting site with merkle whitelists.
            </p>
            <p>
            Created by <code className={styles.code}><a href="https://twitter.com/straightupjac" target="_blank" rel="noreferrer">@straightupjac</a></code>, inspired by <MuiNextLink href="https://github.com/scaffold-eth/scaffold-eth/tree/buyer-mints-nft" target="_blank">Scaffold-eth</MuiNextLink>
            </p>
          </Stack>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/straightupjac/nft-merkle-whitelist-scaffold/tree/main/contracts" target="_blank" rel="noreferrer" className={styles.card}>
            <h2>Contract Setup&rarr;</h2>
            <p>Set up your ERC721 contract, merkle whitelist and deploy.</p>
          </a>

          <a href="https://github.com/straightupjac/nft-merkle-whitelist-scaffold/tree/main/web" target="_blank" rel="noreferrer" className={styles.card}>
            <h2>Web Setup&rarr;</h2>
            <p>Set up your web interface.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank" rel="noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js to a public URL with Vercel.
            </p>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank" rel="noreferrer"
            className={styles.card}
          >
            <h2>Feedback &rarr;</h2>
            <p>
              Noticed an issue? Create an issue, open a PR or reach out to me <a href="https://twitter.com/straightupjac" target="_blank" rel="noreferrer">@straightupjac</a>
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}
